backend/controllers/UsersController.php
<?php
namespace backend\controllers;

use backend\components\AppController;
use backend\models\form\UserForm;
use backend\models\UsersSearch;
use common\enum\Scenario;
use common\models\User;
use common\traits\ModelTrait;
use Yii;


class UsersController extends AppController
{
    use ModelTrait;

    public function actionIndex()
    {
       $searchModel = new UsersSearch();
       $dataProvider = $searchModel->search(Yii::$app->request->get());

       return $this->render('index', [
           'searchModel' => $searchModel,
           'dataProvider' => $dataProvider,
       ]);
    }

    public function actionView($id)
    {
        $user = $this->getModelOr404(User::className(), $id);

        return $this->render('view', [
            'model' => $user,
        ]);
    }

    public function actionCreate()
    {
        $form = new UserForm();
        $form->scenario = Scenario::CREATE;

        if ($form->load(Yii::$app->request->post()) && $user = $form->save()) {
            Yii::$app->session->setFlash('success', 'Пользователь создан');
            return $this->redirect(['view', 'id' => $user->id]);
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    public function actionUpdate($id)
    {
        $user = $this->getModelOr404(User::className(), $id);

        $form = new UserForm();
        $form->setAttributes($user->getAttributes(null, ['password_hash']), false);
        $form->scenario = Scenario::UPDATE;

        if($form->load(\Yii::$app->request->post()) && $user = $form->update($user)) {
            Yii::$app->session->setFlash('success', 'Пользователь обновлен');
            return $this->redirect(['view', 'id' => $user->id]);
        }

        return $this->render('update', ['model'=>$form]);
    }

    public function actionDelete($id)
    {
        return $this->redirect('index');
    }

    public function actionChangeStatus($id, $status=\common\enum\User::STATUS_BLOCK)
    {
        $user = $this->getModelOr404(User::className(), $id);
        $user->status = $status;
        if($user->update(false, ['status'])) {
            $textStatus = $status == \common\enum\User::STATUS_ACTIVE ? 'Активирован' : 'Заблокирован';
            $color = $status == \common\enum\User::STATUS_ACTIVE ? 'success' : 'error';
            \Yii::$app->session->setFlash($color, "Пользователь $textStatus");
        };
        return $this->redirect(['view', 'id' => $user->id]);
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use frontend\components\AppController;
use Yii;
use common\models\form\LoginForm;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use frontend\models\ObjectSearch;
use yii\filters\VerbFilter;
use frontend\models\form\PasswordResetRequestForm;
use frontend\models\form\ResetPasswordForm;
use frontend\models\form\SignupForm;
use yii\web\BadRequestHttpException;
use yii\web\Cookie;

class UserController extends AppController
{

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            $searchModel = new ObjectSearch();
 				$this->view->params['bread'] = '_total';
				$this->view->params['r'] = array();
           $this->view->params['searchModelg'] = $searchModel;
            return true;
        } else {
            return false;
        }
    }
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login','signup','logout','request-password-reset','reset-password'],
                'rules' => [
                    [
                        'actions' => ['login','signup','request-password-reset','reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionLogin()
    {


        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout = 'total';
        $this->disableFooter = false;

        $modelSignup = new SignupForm();
        $model = new LoginForm();
        if (isset(Yii::$app->request->post()['SignupForm'])) {
            if ($modelSignup->load(Yii::$app->request->post()) && $user = $modelSignup->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    \Yii::$app->session->setFlash('success', 'Пользователь зарегистрирован на сайте, поздравляем !');
                    return $this->goHome();
                }
            }

        } else {
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                $referrer = 'realty';
                if (isset($_COOKIE['referrer'])) {
                    $referrer = $_COOKIE['referrer'];
                    Yii::$app->response->cookies->remove('referrer');
                }
                if (!isset($_COOKIE['cityID']) || $_COOKIE['cityID'] == 0 || $_COOKIE['cityID'] == '') {
                    setcookie("cityID", 1);
                }
                return $this->redirect($referrer);
            }
        }
        return $this->render('login', [
            'model' => $model,
            'modelReg' => $modelSignup
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionSignup()
    {
        $this->layout = 'total';
        $this->disableFooter=true;

        echo "<pre>".print_r(Yii::$app->request->post()['SignupForm'], true)."</pre>";
        exit();

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $user = $model->signup()) {
            if (Yii::$app->getUser()->login($user)) {
                \Yii::$app->session->setFlash('success', 'Пользователь зарегистрирован на сайте, поздравляем !');
                return $this->goHome();
            }
        }
        return $this->goBack();
    }

    /**
     * Запрос восстановления пароля
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'total';
        

        $model = new PasswordResetRequestForm();
        
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Проверьте свою электронную почту для получения дальнейших инструкций.');
            } else {
                Yii::$app->session->setFlash('error', 'К сожалению, мы не можем сбросить пароль для электронной почты.');
            }
            return $this->refresh();
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionLoc() {
        echo 123;
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $this->layout = 'total';

        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль был сохранен.');
            return $this->redirect(['user/login']);
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}


frontend/views/user/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
///* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;

$this->registerJsFile(Yii::getAlias('@web') .'js/common_0517.js', ['depends' => [yii\web\JqueryAsset::className()]], \yii\web\View::POS_END);
$this->registerJsFile(Yii::getAlias('@web') .'js/jquery.mousewheel.min.js', ['depends' => [yii\web\JqueryAsset::className()]], \yii\web\View::POS_END);
 
?>
	<link rel="stylesheet" href="css/bootstrap-grid-3.3.1.min.css" />
	<link rel="stylesheet" href="css/font-awesome.min.css" />
	<link rel="stylesheet" href="css/fonts.css" />
	<link rel="stylesheet" href="css/main_0517.css" />
	<link rel="stylesheet" href="css/media_0517.css" />


	<div class="container">
		<div class="row">
			<div class="col-sm-3 hidden-xs"></div>
			<div class="col-sm-6 form-container">
				<div class="form-type enabled" id="enter">Вход</div>
				<div class="form-type" id="reg">Регистрация</div>
				<div class="enter-form" id="reg-f" style="display: none;">
                    <?php $formRegister = ActiveForm::begin() ?>
                    <?= $formRegister->field($modelReg, 'email')->textInput(['placeholder' => 'Email', 'class' => false])->label(false) ?>
                    <?= $formRegister->field($modelReg, 'password')->passwordInput(['placeholder' => 'Пароль не менее 6 символов', 'class' => false])->label(false) ?>
                    <?= $formRegister->field($modelReg, 'confirm_password')->passwordInput(['placeholder' => 'Пароль повторно', 'class' => false])->label(false) ?>
					<div class="check">
                        <?= $formRegister->field($modelReg, 'accept')->checkbox([
                            'id' => 'accept',
                            'label' => 'Я согласен с <a href="#" class="terms-a">условиями сайта</a>',
                            'template' => '<div class="checkbox">{beginLabel}{input}{labelTitle}<br/>{error}{endLabel}{hint}</div>'
                        ]) ?>
<!--						<label for="accept">Я согласен с <a href="#" class="terms-a">условиями сайта</a></label>-->
					</div>
                    <div class="clearfix"></div>
					<div class="captcha">
                        <?= $formRegister->field($modelReg, 'recaptcha')->widget(
                            \himiklab\yii2\recaptcha\ReCaptcha::className(),
                            ['siteKey' => '6LeCdCMUAAAAANwK2oSh1w-ddN6auFIDCreHu_FV']
                        )->label(false) ?>
                    </div>
                    <?= Html::submitInput('Зарегестрироваться', ['name' => 'register'])?>
                    <?php ActiveForm::end(); ?>
                </div>
				<div class="enter-form" id="enter-f">
                    <?php $form = ActiveForm::begin() ?>
                    <?= $form->field($model, 'email',[
						'options'=>[
							
						],
						'template'=>'{input}{error}'
					])->textInput([
						'type'=>'email',
						'class'=>'l-email',
						'placeholder'=>$model->getAttributeLabel('Email'),
					]) ?>
					<?= $form->field($model, 'password',[
						'options'=>[
							'class'=>'l-password',
						],
						'template'=>'{input}{error}'
					])->passwordInput([
						'type'=>'password',
						'class'=>'l-email',
						'placeholder'=>$model->getAttributeLabel('Ваш пароль'),
					]) ?>

                    <div class="resetBlock">
                        <a href="/user/request-password-reset" class="resetPass">Забыли пароль?</a>
                    </div>
					<?= Html::submitInput('Вход') ?>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
	<!--[if lt IE 9]>
	<script src="libs/html5shiv/es5-shim.min.js"></script>
	<script src="libs/html5shiv/html5shiv.min.js"></script>
	<script src="libs/html5shiv/html5shiv-printshiv.min.js"></script>
	<script src="libs/respond/respond.min.js"></script>
	<![endif]-->

<style>
    .login-box{margin-bottom: 20px;}
    @media only screen and (max-width : 1200px) {
        .login-box{padding-left: 20px !important;}
    }
    @media only screen and (max-width : 768px) {
        .login-box h3, .login-box form{padding-left: 55px !important;}
    }
</style>
<!--
<div class="container">
    <div class="row">

        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 login-box">

            <h3><?/*= $this->title */?> / <a href="<?/*= \yii\helpers\Url::to(['user/signup']) */?>">Регистрация</a></h3>
            
            <?/*= $form->field($model, 'username',[
                'options'=>[
                    'class'=>'form-group has-feedback',
                ],
                'template'=>'{input}<span class="glyphicon glyphicon-user form-control-feedback"></span>{error}'
            ])->textInput([
                'class'=>'form-control',
                'placeholder'=>$model->getAttributeLabel('username'),
            ]) */?>

            --><?/*= $form->field($model, 'password', [
                'options'=>[
                    'class'=>'form-group has-feedback',
                ],
                'template'=>'{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span>{error}'
            ])->passwordInput([
                'class'=>'form-control',
                'placeholder'=>$model->getAttributeLabel('password'),
            ]) */?>

           <!-- <div class="row">
                <div class="col-xs-8">
                    <?/*= $form->field($model, 'rememberMe',[
                        'template' => "<div class=\"checkbox icheck\"><label>{input} {label}</label></div>{error}",
                    ])->checkbox() */?>
                    <?/*= Html::a('Забыли пароль?', ['user/request-password-reset']) */?>
                </div>
                <div class="col-xs-4" style="padding-right:0px;">
<input type="submit" value="Зарегестрироваться">
                </div>
            </div>-->
            <!-- <a href="#">I forgot my password</a><br>-->
            <!-- <a href="register.html" class="text-center">Register a new membership</a>-->


<!--            <form action="" method="post">-->
<!--                <div class="form-group">-->
<!--                    <input type="text" class="form-control" placeholder="Identifiant ou Email">-->
<!--                </div>-->
<!---->
<!--                <div class="form-group">-->
<!--                    <input type="password" class="form-control" placeholder="********">-->
<!--                </div>-->
<!---->
<!--                <div class="form-group">-->
<!--                    <input type="checkbox" id="s"> <label for="s" >Se souvenir de moi</label >-->
<!--                </div>-->
<!---->
<!--                <div class="form-group">-->
<!--                    <input type="submit" class="btn btn-success" value="Se connecter">-->
<!--                </div>-->
<!---->
<!--            </form>-->
  <!--      </div>
    </div>
</div>-->
</div>

<?php /*
<div class="container">

            <div class="login-box">
                <h3><?= $this->title ?> / <a href="<?= \yii\helpers\Url::to(['user/signup']) ?>">Регистрация</a></h3>
                <!-- /.login-logo -->
                <div class="login-box-body">
                    <?php $form = ActiveForm::begin() ?>

                    <?= $form->field($model, 'username',[
                        'options'=>[
                            'class'=>'form-group has-feedback',
                        ],
                        'template'=>'{input}<span class="glyphicon glyphicon-user form-control-feedback"></span>{error}'
                    ])->textInput([
                        'class'=>'form-control',
                        'placeholder'=>$model->getAttributeLabel('username'),
                    ]) ?>

                    <?= $form->field($model, 'password', [
                        'options'=>[
                            'class'=>'form-group has-feedback',
                        ],
                        'template'=>'{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span>{error}'
                    ])->passwordInput([
                        'class'=>'form-control',
                        'placeholder'=>$model->getAttributeLabel('password'),
                    ]) ?>

                    <div class="row">
                        <div class="col-xs-8">
                            <?= $form->field($model, 'rememberMe',[
                                'template' => "<div class=\"checkbox icheck\"><label>{input} {label}</label></div>{error}",
                            ])->checkbox() ?>
                            <?= Html::a('Забыли пароль?', ['user/request-password-reset']) ?>
                        </div>
                        <div class="col-xs-4">
                            <?= Html::submitButton('Вход', [
                                'class' => 'btn btn-primary btn-block btn-flat',
                                'name' => 'login-button'
                            ]) ?>

                        </div>
                    </div>
                    <?php ActiveForm::end(); ?>

                    <!-- <a href="#">I forgot my password</a><br>-->
                    <!-- <a href="register.html" class="text-center">Register a new membership</a>-->

                </div>
            </div>

</div>
 */ ?>

frontend/views/user/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\form\ResetPasswordForm */

$this->title = 'Поменять пароль';
?>
<style>
    .login-box{margin-bottom: 20px;}
    @media only screen and (max-width : 1200px) {
        .login-box{padding-left: 20px !important;}
    }
    @media only screen and (max-width : 768px) {
        .login-box h3, .login-box p, .login-box form{padding-left: 55px !important;}
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 login-box">
            <h3><?= $this->title ?></h3>
            <p class="m_t_20">
                Пожалуйста, введите адрес электронной почты, указанный в параметрах вашей учётной записи. На него будет
                отправлен специальный проверочный код.
                После его получения вы сможете ввести новый пароль для вашей учетной записи.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 login-box">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'email', [
                    'options' => [
                        'class' => 'form-group has-feedback',
                    ],
                    'template' => '{input}<span class="glyphicon glyphicon-envelope form-control-feedback"></span>{error}'
                ])->textInput([
                    'class' => 'form-control',
                    'placeholder' => $model->getAttributeLabel('email'),
                ]) ?>

                <div class="row">
                    <div class="col-xs-6">
                        <?= Html::submitButton('Восстановить', [
                            'class' => 'btn btn-primary btn-block',
                            'name' => 'request-password-reset-token-button'
                        ]) ?>
                    </div>
                    <div class="col-xs-6">
                        <?= Html::a('Отмена', ['user/login'], [
                            'class' => 'btn btn-primary btn-block btn-flat',
                        ]) ?>
                    </div>
                </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>


frontend/views/user/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\form\ResetPasswordForm */

$this->title = 'Сброс пароля';
?>

<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="reset-password-box">

                <h2><?= $this->title ?></h2>

                <div class="reset-password-box-body">
                    <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                    <p>Пожалуйста, выберите ваш новый пароль:</p>
                    <?= $form->field($model, 'password', [
                        'options' => [
                            'class' => 'form-group has-feedback',
                        ],
                        'template' => '{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span>{error}'
                    ])->passwordInput([
                        'class' => 'form-control',
                        'placeholder' => $model->getAttributeLabel('password'),
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>

    </div>
</div>

frontend/views/user/signup.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\form\SignupForm */

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    .signup-box{margin-bottom: 20px;}
    @media only screen and (max-width : 1200px) {
        .signup-box{padding-left: 20px !important;}
    }
    @media only screen and (max-width : 768px) {
        .signup-box h3, .signup-box form{padding-left: 55px !important;}
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 signup-box">
            <h3><?= $this->title ?> / <a href="<?= \yii\helpers\Url::to(['user/login']) ?>">Вход</a></h3>

            <div class="signup-box-body">
                <?php $form = ActiveForm::begin() ?>

                <?= $form->field($model, 'full_name', [
                    'options' => [
                        'class' => 'form-group has-feedback',
                    ],
                    'template' => '{input}<span class="glyphicon glyphicon-sunglasses form-control-feedback"></span>{error}'
                ])->textInput([
                    'class' => 'form-control',
                    'placeholder' => $model->getAttributeLabel('full_name'),
                ]) ?>

                <?= $form->field($model, 'username', [
                    'options' => [
                        'class' => 'form-group has-feedback',
                    ],
                    'template' => '{input}<span class="glyphicon glyphicon-user form-control-feedback"></span>{error}'
                ])->textInput([
                    'class' => 'form-control',
                    'placeholder' => $model->getAttributeLabel('username'),
                ]) ?>

                <?= $form->field($model, 'email', [
                    'options' => [
                        'class' => 'form-group has-feedback',
                    ],
                    'template' => '{input}<span class="glyphicon glyphicon-envelope form-control-feedback"></span>{error}'
                ])->textInput([
                    'class' => 'form-control',
                    'placeholder' => $model->getAttributeLabel('email'),
                ]) ?>

                <?= $form->field($model, 'password', [
                    'options' => [
                        'class' => 'form-group has-feedback',
                    ],
                    'template' => '{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span>{error}'
                ])->passwordInput([
                    'class' => 'form-control',
                    'placeholder' => $model->getAttributeLabel('password'),
                ]) ?>

                <div>
                    <?= $form->field($model, 'captcha')->widget(\yii\captcha\Captcha::className(), [
                        'template' => '<div class="d_inline_block">{image}</div><div class="d_inline_block w90 v_middle">{input}</div>',
                        'options'=>[
                            'class'=>'form-control',
                            'placeholder' => $model->getAttributeLabel('captcha'),
                        ]
                    ])->label(false) ?>
                </div>

                <div class="row">
                    <div class="col-xs-6">
                        <?= Html::submitButton('Регистрация', [
                            'class' => 'btn btn-primary btn-block',
                            'name' => 'signup-button'
                        ]) ?>
                    </div>
                    <div class="col-xs-6">
                        <?= Html::a('Отмена', ['site/index'], [
                            'class' => 'btn btn-primary btn-block btn-flat',
                        ]) ?>
                    </div>
                </div>
                <?php ActiveForm::end(); ?>

                <!-- <a href="#">I forgot my password</a><br>-->
                <!-- <a href="register.html" class="text-center">Register a new membership</a>-->

            </div>
        </div>

    </div>
</div>