backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\components\AppController;
use Yii;
use common\models\form\LoginForm;

class SiteController extends AppController
{
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id=='error') {
                $this->layout ='@frontend/views/layouts/total';
                $this->disableFooter = true;
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'load-district' => [
                'class'=>\common\components\actions\LoadDistrictAction::className()
            ]
        ];
    }


    /**
     * Dashboard
     *
     */
    public function actionIndex()
    {
        $this->layout = 'dashboard';
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }


        $this->layout = 'base';
        $this->bodyClass = 'hold-transition login-page';

        $model = new LoginForm();
        $model->loginAdmin = true;
        
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\components\actions\realty\LoadDistrictAction;
use common\components\ThumbHelper;
use common\models\Banners;
use common\models\Articles;
use common\models\Pages;
use common\models\Realty;
use common\models\User;
use common\models\City;
use common\models\District;
use common\traits\ModelTrait;
use frontend\components\actions\SiteErrorAction;
use frontend\components\AppController;
use frontend\modules\mortgage_calculation\models\CalculatorForm;
use frontend\models\ObjectSearch;
use common\models\RealtyImage;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\HtmlPurifier;
use yii\helpers\Json;
use yii\helpers\Url;
//use yii\web\ErrorAction;
use yii\web\NotFoundHttpException;
use \common\components\TranslitHelper;
use common\enum\User as UserType;
use common\components\actions;

/**
 * Site controller
 */
class SiteController extends AppController
{
    use ModelTrait;
    public $user;
    public $bread;
    public $userRoles = array(
        1 => 'Собственник',
        2 => 'Подрядчик',
        3 => 'Застройщик',
        4 => 'Агенство'
    );
    
    public function beforeAction($action)
    {
       if (parent::beforeAction($action)) {
            if ($action->id=='error') {
                $this->layout ='total';
                $this->disableFooter = false;
            }
            $searchModel = new ObjectSearch();
            $this->view->params['searchModelg'] = $searchModel;
			$this->view->params['ObjectSearch'] = [];
            return true;
        } else {
            return false;
        }
    }
	

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => SiteErrorAction::className(),
            ],
            'captcha' => [
                'class' => \yii\captcha\CaptchaAction::className(),
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'minLength' => 3,
                'maxLength' => 4,
            ],
            'load-district' => [
                'class'=>\common\components\actions\LoadDistrictAction::className()
            ],
            'vip-image' => [
                'class'=>\frontend\components\actions\VipImageAction::className()
            ],
            'logo-header' => [
                'class'=>\frontend\components\actions\LogoHeaderAction::className()
            ]
        ];
    }
    
    public function actionIndex()
    {
        //var_dump(\yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch' => ['test']]));
        //return $this->redirect('search-objects');
        $this->layout='total';
		$key = 'new_objects'; 

		/*$new_objects = Yii::$app->cache->getOrSet($key, function () {
			return Realty::find()->joinWith(['attr','user'])->andFilterWhere([
				'realty.status' => \common\enum\Realty::STATUS_PUBLIC
			])->limit(3)->orderBy(['id' => SORT_DESC])->all();
		});*/


        $new_objects =  Realty::find()->joinWith(['attr','user'])->andFilterWhere([
            'realty.status' => \common\enum\Realty::STATUS_PUBLIC
        ])->limit(3)->orderBy(['id' => SORT_DESC])->all();

//var_dump($new_objects);
        foreach ($new_objects as $key => $value) {

            $new_objects[$key] = array(
                "obj" => $value,
                "city_name" => "",
                "user_type" => ""
            );
            //var_dump($value->id);
           // var_dump($value->attr);
            if ($value->attr) {
                $city = City::find()->where(["id" => (int)$value->attr->city_id])->one();
                $new_objects[$key]["city_name"] = $city->title;
            }
            /**
             * Если тип юзера застройщик то будем выводить надпись
             */
            if($value->user->type == UserType::TYPE_CREATOR){
                $new_objects[$key]["user_type"] = UserType::Type($value->user->type);
            }
        }
//exit;
		$key = 'new_housing_estate'; 

        /*$new_housing_estate = Yii::$app->cache->getOrSet($key, function () {
			return Realty::find()->joinWith(['attr','user'])->andFilterWhere(['not', 'realty_attr.housing_estate=""'])->limit(3)->orderBy(['id' => SORT_DESC])->all();
		});*/

        $new_housing_estate = Realty::find()->joinWith(['attr','user'])->andFilterWhere(['not', 'realty_attr.housing_estate=""'])->limit(3)->orderBy(['id' => SORT_DESC])->all();


        foreach ($new_housing_estate as $key => $value) {

            $new_housing_estate[$key] = array(
                "obj" => $value,
                "city_name" => "",
                "user_type" => ""
            );

            $city = City::find()->where(["id" => (int)$value->attr->city_id])->one();
            $new_housing_estate[$key]["city_name"] = $city->title;

            $new_housing_estate[$key]["user_type"] = $value->user->type;

           // $new_housing_estate[$key]["user_name"] = $value->user->full_name;
        }

		$key = 'new_zastr'; 
		/*$new_zastr = Yii::$app->cache->getOrSet($key, function () {
			return Realty::find()->joinWith(['attr','user'])
                        ->andFilterWhere(['users.type'=>3])
                        ->limit(3)
                        ->orderBy(['id' => SORT_DESC])
                        ->all();
		});*/

		$new_zastr = Realty::find()->joinWith(['attr','user'])
            ->andFilterWhere(['users.type'=>3])
            ->limit(3)
            ->orderBy(['id' => SORT_DESC])
            ->all();

		//var_dump($new_zastr);
        foreach ($new_zastr as $key => $value) {
            $new_zastr[$key] = array(
                "obj" => $value,
                "city_name" => "",
                "user_type" => ""
            );

            if ($value->attr !== null) {
                $city = City::find()->where(["id" => (int)$value->attr->city_id])->one();
                $new_zastr[$key]["city_name"] = $city->title;
            }
           // var_dump($value->user->company);
            //$new_zastr[$key]["user_type"] = $value->user->full_name;
        }
		$this->view->registerMetaTag(
		['name' => 'keywords','content' => 'Жилые комплексы и Новостройки Москвы и Подмосковья. Продажа квартир в Новостройках и Жилых Комплексах Москвы и Подмосковья',]);
		$this->view->registerMetaTag(['name' => 'description','content' => 'Новостройки Москвы, Новой Москвы и Подмосковья. Купить квартиру в Жилых Комплексах от застройщиков - самая большая и актуальная база Московской недвижимости',]
		);
        return $this->render('new_index', [
            'new_objects' => $new_objects,
            'new_housing_estate' => $new_housing_estate,
            'new_zastr' => $new_zastr
        ]);
    }

    /**
     * Просмотр объявления
     */
    public function actionAdvertisement($id='')
    {
        $id = HtmlPurifier::process($id);
        $realty = Realty::find()->where(['id'=>$id])->with(['attr','desc','images','docs'])->one();
        if($realty) {
			$ObjectSearch = [];
            $this->layout = 'total';
            Yii::$app->stat->regShow('realty', $realty->id);
			$breadCity = (isset($realty->attr['city_id']) && (!empty($realty->attr['city_id']))) ? City::find()->where(["id" => (int)$realty->attr['city_id']])->one() :[] ;
			$breadDistrict = (isset($realty->attr['district_id']) && (!empty($realty->attr['district_id']))) ? District::find()->where(["id" => (int)$realty->attr['district_id']])->one() :[] ;
			if(isset($breadCity) && (!empty($breadCity))){
				$ObjectSearch['city_id'] = $breadCity['id'];
				$this->view->params['breadcrumbs'][] = [
					'label' => $breadCity['title'],
					'url' => \yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch' => $ObjectSearch]),
					'template' => "<li><b>{link}</b></li>\n", // template for this link only
				];
			}
			if(!empty($realty->user->typeName())){
				$ObjectSearch['option'] = \common\enum\User::TYPE_CREATOR;
				$this->view->params['breadcrumbs'][] = [
					'label' => $realty->user->typeName(),
					'url' => \yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch' => $ObjectSearch]),
					'template' => "<li><b>{link}</b></li>\n", // template for this link only
				];
			}
			if(!empty($realty->attr->rooms)){
				$ObjectSearch['room'.$realty->attr->rooms] = 1;
				$this->view->params['breadcrumbs'][] = [
					'label' => Yii::t('app', '{n, number} {n, plural, one{Комната} few{Комнаты} many{Комнаты} other{Комнаты}}', ['n'=>$realty->attr->rooms]),
					'url' => \yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch' => $ObjectSearch]),
					'template' => "<li><b>{link}</b></li>\n", // template for this link only
				];
			}
			if(isset($breadDistrict) && (!empty($breadDistrict))){
				$ObjectSearch['district_id'] = $breadDistrict['id'];
				$this->view->params['breadcrumbs'][] = [
					'label' => $breadDistrict['title'],
					'url' => \yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch' => $ObjectSearch]),
					'template' => "<li><b>{link}</b></li>\n", // template for this link only
				];
			}
			if(!empty($realty->desc->title)){
				$ObjectSearch['room'.$realty->attr->rooms] = 1;
				$this->view->params['breadcrumbs'][] = [
					'label' => \yii\helpers\Html::encode($realty->desc->title),
					'template' => "<li><span style='color: rgb(41, 171, 226);'>{link}</span></li>\n", // template for this link only
				];
			}

			$this->view->registerMetaTag([
				'name' => 'keywords',
				'content' => $realty->desc->title
			]);

            return $this->render('advertisement', ['realty'=>$realty]);
        }

        throw new NotFoundHttpException(Yii::$app->params['error404']);
    }

    public function actionSearchFilter($page = 1)
    {
        if(!empty(Yii::$app->request->post())){
            $searchParams = Yii::$app->request->post();
        } else {
            $searchParams = Yii::$app->request->getQueryParams();
        }

        $searchModel = $this->view->params['searchModelg'];

        $filter = [];
        $rooms = 0;

frontend/views/site/_breadcrumb.php
<style>
    #breadcrumb-total .row{margin-left:-23px;}
    #breadcrumb-total .row > div{padding-left:0px;padding-right:0px;}
    @media only screen and (max-width : 940px) {
        .breadcrumb{padding-left:22px;}
    }
    @media only screen and (max-width : 768px) {
        .breadcrumb{padding-left:56px;}
    }
</style>
<?php $href = '/';?> 
<div class="container">
    <div id="breadcrumb-total">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="<?= $href ?>"><span style="color:red">Главная</span></li></a>
                    <?php $href .= 'search-objects';
					?>
                    <?php if(!empty($this->params['city'])){ 
						$href .= '?ObjectSearch[city_id]='.$this->params['city']->id;
					?>
					<li><a href="<?= $href ?>"><span id="city-name"><?= $this->params['city']->title ?></span></a></li>
                    <?php } ?>
                </ol>
            </div>
        </div>
    </div>
</div>


frontend/views/site/_item_object.php
<?php

    use common\components\ThumbHelper;
    use common\components\TranslitHelper;
    use common\enum\District;
    use common\enum\City;
    use yii\helpers\Html;

    $cityName = TranslitHelper::transliteration(City::Lists($model->attr->city_id));


?>
<div class="admy-item">
    <a href="<?= \yii\helpers\Url::to(['site/advertisement', 'id'=>$model->id]) ?>" data-pjax="0" target="_blank">
        <div class="row">
            <div class="col-md-4">
                <?php
                if(!$model->vip):
                    $image = ThumbHelper::thumbnailImg($model->mainImage(), 225, 162, ThumbHelper::THUMBNAIL_OUTBOUND, [], false);
                else:
                    $image = \yii\helpers\Url::to(['site/vip-image', 'url'=> ThumbHelper::thumbnailImg($model->mainImage(), 225, 162, ThumbHelper::THUMBNAIL_OUTBOUND, [], false)]);
                endif ?>
                <?= Html::img($image, ['alt' => $model->attr->rooms . ' комн, р-н ' . District::Lists($model->attr->district_id), 'class' => 'preview'])?>
            </div>
            <div class="col-md-8">
                <?php if (file_exists('/upload/citesLogo/' . $cityName . '.png')) : ?>
                    <img src="/upload/citesLogo/<?= $cityName ?>.png" alt="<?= City::Lists($model->attr->city_id)?>" class="cityLogo">
                <?php endif; ?>
                <?php if (!empty($model->flats)) : ?>
                    <div class="builder"><?= $model->attr->housing_estate ?></div>
                    <div class="clearfix"></div>
                    <div class="address-wrap">
                        <div class="address-text">Застройщик: <?= $model->user->buildcompany ?></div>
                    </div>
                    <ul class="prices-list">
                        <?php
                            $icount = 1;
                            foreach ($model->flats as $flat) :
                        ?>
                                <li><span class="rooms"><?= $flat->attr->rooms?></span> комн от <span class="price"><?= preg_replace('#(?<=\d)(?=(\d{3})+$)#', ' ', $flat->price) ?> <span class="rub">руб</span></span></li>
                        <?php
                                if ($icount == 3)
                                    break;
                                $icount++;
                            endforeach;
                        ?>
                    </ul>
                <?php else: ?>
                    <div class="decs-list">
                        <ul class="houseInfo">
                            <?php if ($model->attr->rooms) : ?>
                                <li><span><?= $model->attr->rooms?></span>:комн,</li>
                            <?php endif; ?>
                            <?php if ($model->attr->area_living) : ?>
                                <li>50/37/10,</li>
                            <?php endif; ?>
                            <?php if ($model->attr->floor) : ?>
                                <li>эт:<?= $model->attr->floor ?>/<?= $model->attr->floors ?></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                    <div class="address-wrap">
                        <?php if (District::Lists($model->attr->district_id)) : ?>
                            <div class="address-text">рн: <?= District::Lists($model->attr->district_id) ?></div>
                        <?php endif; ?>
                        <?php if ($model->attr->street) : ?>
                           <div class="address-text">ул: <?= $model->attr->street ?></div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="toBottom">
            <div class="deadline">срок сдачи<span><?= intval((date('n', $model->deadline)+2)/3) . " кв " . date("Y", $model->deadline) ?></span></div>
            <?php if (empty($model->flats)) : ?>
                <div class="price-list"><?= preg_replace('#(?<=\d)(?=(\d{3})+$)#', ' ', $model->price) ?> руб</div>
            <?php endif; ?>
        </div>
    </a>
    <div class="userButtons">
        <?= $this->render('/layouts/_btn_favorite', ['model'=>$model]) ?>
        <?= $this->render('/layouts/_btn_spy_price', ['model'=>$model]) ?>
    </div>
</div>

<?php  if(($index + 1) % 3 == 0): ?>
    <div class="banner-block">
        <?= \frontend\components\widget\BannerBig::widget() ?>
    </div>
<?php endif ?>

frontend/views/site/_item_object_map.php
<?php
use common\components\ThumbHelper;
use common\enum\District;

?>
<div class="row">
    <div class="col-xs-12">
        <div class="content-list">
            <div class="admy-item">
                <a href="<?= \yii\helpers\Url::to(['site/advertisement', 'id'=>$model->id]) ?>">
                    <div class="row">
                        <div class="col-md-4">
                            <?php if(!$model->vip): ?>
                                <div class="preview" style="background-image: url(<?= ThumbHelper::thumbnailImg($model->mainImage(), 768, 576, ThumbHelper::THUMBNAIL_OUTBOUND, [], false) ?>)"></div>
                            <?php else: ?>
                                <div class="preview" style="background-image: url(<?= \yii\helpers\Url::to(['site/vip-image', 'url'=>ThumbHelper::thumbnailImg($model->mainImage(), 768, 576, ThumbHelper::THUMBNAIL_OUTBOUND, [], false)]) ?>"></div>
                            <?php endif ?>
                        </div>
                        <div class="col-md-8">
                            <div class="price-list"><?= preg_replace('#(?<=\d)(?=(\d{3})+$)#', ' ', $model->price) ?> руб</div>
                            <div class="clearfix"></div>
                            <div class="builder"><?= $model->attr->housing_estate ? $model->attr->housing_estate : '' ?></div>
                            <div class="address-wrap">
                                <?php if ($model->attr->district->title) : ?> <div class="address-text">рн: <?= $model->attr->district->title ?></div> <?php endif; ?>
                                <?php if ($model->attr->street) : ?> <div class="address-text">ул: Зои космедемьянской</div> <?php endif ?>
                            </div>
                        </div>
                    </div>
                    <div class="toBottom">
                        <div class="deadline"><?= intval((date('n', $model->deadline)+2)/3) . " кв " . date("Y", $model->deadline) ?></div>
                    </div>
                    <div class="userButtons">
                        <?= $this->render('/layouts/_btn_favorite', ['model'=>$model]) ?>
                        <?= $this->render('/layouts/_btn_spy_price', ['model'=>$model]) ?>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

frontend/views/site/advertisement.php
<?php
$this->title = 'Просмотр объекта';
//echo \common\enum\City::Lists($realty->attr->city_id);

function price_format($price) {
    return preg_replace('#(?<=\d)(?=(\d{3})+$)#', ' ', $price);
}

?>
<style>
    #banner-big img{margin-top:-20px;margin-bottom:-10px;}
    #banners1 .row .col-lg-4{padding-left:8px;padding-right:8px;}
    @media only screen and (max-width:768px) {
        /*#banners1 .row .col-lg-4{left:26px !important;}*/
        #banner-big .box-banner{left: 17px !important;}
        #btn-all-objects button{margin-left:28px !important;margin-bottom:25px !important;}

        #contact-owner{padding-right:0px !important;}
        #contact-owner .col-xs-12{padding-right:0px !important;}
        #contact-owner .box-header{padding-left:35px !important;}
        #contact-owner .box-body{padding-left:30px !important;}
        #contact-owner img{margin-left:0px !important;}
    }
</style>

<div class="object-page">

<?= $this->render('@frontend/views/layouts/_object_info', ['realty'=>$realty]) ?>

<?= $this->render('@frontend/views/layouts/_object_desc', ['realty'=>$realty]) ?>

<?= $this->render('@frontend/views/layouts/_object_on_map', ['realty'=>$realty]) ?>

<?= $this->render('@frontend/views/layouts/_object_link_items', ['realty'=>$realty]) ?>

<?php 
if($realty->type != \common\enum\Realty::TYPE_APARTMENT_HOUSE): ?>
    <?= \frontend\modules\mortgage_calculation\widgets\CalculationWidget::widget([
        'price' => $realty->price,
        'title' => $realty->desc->title
    ]) ?>
<?php endif ?>

<?= $this->render('@frontend/views/layouts/_object_docs', ['realty'=>$realty]) ?>

<?= $this->render('@frontend/views/layouts/_contact_owner', ['user'=>$realty->user, 'realty'=>$realty]) ?>

<?= \frontend\components\widget\ObjectsNear::widget([
    'geo_lat'=>$realty->geo_lat,
    'geo_lng'=>$realty->geo_lng
]) ?>

</div>

<div class="container">
    <div class="object-page">
        <div class="d-table">
            <div class="d-row">
                <div class="heading-line">
                    <h2 class="h2">Новостройки от застройщика <?= \common\enum\City::Lists($realty->attr->city_id)?></h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="bg-newBuildings">
    <?php echo \frontend\components\widget\BannerBiggest::run(array('city_id' => ((isset($_COOKIE['cityID'])) && (!empty($_COOKIE['cityID']))) ? $_COOKIE['cityID'] : 0 )) ?>
</div>

<?= \frontend\components\widget\BannerSmall::widget() ?>
<?= \frontend\components\widget\BannerMiddleHorizontal::widget() ?>
<div class="container">
    <?= \frontend\components\widget\BannerBig::widget() ?>
</div>

<?= $this->render('@frontend/views/layouts/_btn_all_objects', ['realty'=>$realty]) ?>

frontend/views/site/articles_item.php
<?php
$block='';
?>
<div class="text-content">
    <div class="text-content-title"><?=$article['title']?></div>
    <div class="text-content-desc"><?=$article['text']?></div>
</div>



frontend/views/site/new_index.php
<?php 
use common\components\ThumbHelper;
use common\enum\User;
$this->title='«Все Новостройки» - База новостроек Москвы, Подмосковья и Новой Москвы от застройщиков';
?>

<div class="general">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                <h2><a href="<?
                    unset($this->params['ObjectSearch']['option']);
                    unset($this->params['ObjectSearch']['housing_estate']);
                    echo \yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch'=> array_merge($this->params['ObjectSearch'], ['novostroyki'=>1])]);?>" class="" >Все новостройки</a></h2>
            </div>
        </div>
        <div class="row">
            <?
            foreach ($new_objects as $key => $value) {
                ?>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 stroyki_main_item">
                    <div class="box_house">
                        <div class="strong_size bg_1" style="background-image:url(<?= ThumbHelper::thumbnailImg($value["obj"]->mainImage(), 300, 250, ThumbHelper::THUMBNAIL_OUTBOUND, [], false) ?>);">
                            <a href="<?= \yii\helpers\Url::to(['site/advertisement', 'id'=>$value["obj"]->id]) ?>">
                                <p class="city_p"><?=$value["city_name"]?><br>
                                    <?=$value["obj"]->attr->rooms?> комнатная</p>
                                <p class="price_p"><?=number_format($value["obj"]->price, 0, ","," ")?> <span>руб</span></p>

                                <p class="developer_p"><?=$value["obj"]->user->buildcompany?></p>

                            </a>
                        </div>
                    </div>
                </div>
                <?
            }
            ?>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                <h2><a href="<?
                    unset($this->params['ObjectSearch']['novostroyki']);
                    unset($this->params['ObjectSearch']['option']);
                    echo \yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch' => array_merge($this->params['ObjectSearch'], ['housing_estate'=>1])]);?>">Все жилые комплексы</a></h2>
            </div>
        </div>
        <div class="row">
            <?
            foreach ($new_housing_estate as $key => $value) {
                ?>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 stroyki_main_item">
                    <div class="box_house">
                        <div class="strong_size bg_4" style="background-image:url(<?= ThumbHelper::thumbnailImg($value["obj"]->mainImage(), 300, 250, ThumbHelper::THUMBNAIL_OUTBOUND, [], false) ?>);">
                            <a href="<?= \yii\helpers\Url::to(['site/advertisement', 'id'=>$value["obj"]->id]) ?>">
                                <p class="city_p"><?=$value["city_name"]?></p>
                                <!--<p class="jk_p"><?=($value["obj"]->attr->gkh_name)?$value["obj"]->attr->gkh_name: 'жк Солнечный берег' ?></p>-->
                                <p class="jk_p"><?=($value["obj"]->attr->housing_estate)?$value["obj"]->attr->housing_estate: '' ?></p>
                                <p class="sm_price">От :  <?=number_format($value["obj"]->price, 0, ","," ")?>  руб  м2</p>

                                <?php if ($value["user_type"] == User::TYPE_CREATOR): ?>
                                    <p class="developer_p">Застройщик : <?=$value["obj"]->user->buildcompany?></p>
                                <?php endif; ?>
                            </a>
                        </div>
                    </div>
                </div>
                <?
            }
            ?>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                <h2><a href="<?
                    unset($this->params['ObjectSearch']['novostroyki']);
                    unset($this->params['ObjectSearch']['housing_estate']);
                    echo \yii\helpers\Url::toRoute(['site/search-objects', 'ObjectSearch' => array_merge($this->params['ObjectSearch'], ['option'=>\common\enum\User::TYPE_CREATOR])]);?>">Все застройщики</a></h2>
            </div>
        </div>
        <div class="row">
            <?
            foreach ($new_zastr as $key => $value) {
                ?>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 stroyki_main_item">
                    <div class="box_house">
                        <div class="strong_size bg_7" style="background-image:url(<?= ThumbHelper::thumbnailImg($value["obj"]->mainImage(), 300, 250, ThumbHelper::THUMBNAIL_OUTBOUND, [], false) ?>);">
                            <a href="<?= \yii\helpers\Url::to(['site/advertisement', 'id'=>$value["obj"]->id]) ?>">
                                <p class="city_p last_city_p"><?=$value["city_name"]?></p>
                                <p class="developer_p">Застройщик:</p>
                                <p class="big_devel_p"><?=$value["obj"]->user->buildcompany?></p>
                                <?php if($value["obj"]->user->publicLogo() !== 'notFind'): ?>
                                <div style="background-image:url(<?=$value["obj"]->user->publicLogo()?>);"></div>
                                <?php endif; ?>
                            </a>
                        </div>
                    </div>
                </div>
                <?
            }
            ?>
        </div>
        <div class="row" style="margin-left:-15px;">
            <?= frontend\components\widget\BannerSmall::widget(['dop_class' => '']) ?>
            <?= frontend\components\widget\BannerMiddleHorizontal::widget() ?>
            <?= frontend\components\widget\BannerBig::widget() ?>
        </div>
        <div class="row main-text">
            <div class="col-lg-8 col-md-8 col-sm-7 col-xs-12">
                    <?= \frontend\components\widget\ShowArticle::run(array('pos' => 3, 'city_id' => (isset($_COOKIE['cityID']) && !empty($_COOKIE['cityID'])) ? $_COOKIE['cityID'] : 0 ));?>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
                <div class="banners-right">
                    <!--<div class="banner-right col-lg-12 col-md-12 col-sm-6 col-xs-12 br1">баннер 300на 250 пикс<br>жёстко</div>
                    <div class="banner-right col-lg-12 col-md-12 col-sm-6 col-xs-12 br2">баннер 300на 250 пикс<br>жёстко</div>-->

                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- авто -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-9616416554119262"
                         data-ad-slot="1682961932"
                         data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>